## Introduction to Numpy
* Numerical Python
* Linear Algebra for Python
* Has bindings to C library
* High Performance Scientific Computing

In [1]:
import numpy as np

Numpy ndarray - A multidimensional Array Object
* HOMOGENOUES DATA

In [2]:
lst_data = list(range(1, 11))
print(lst_data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [185]:
np.array(lst_data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [187]:
e = np.array([lst_data])

In [189]:
print(e.shape)
print(e.ndim)
print(e)

(1, 10)
2
[[ 1  2  3  4  5  6  7  8  9 10]]


In [4]:
np1 = np.array(lst_data)

In [5]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
print(type(np1))

<class 'numpy.ndarray'>


### Shape

In [7]:
np1.shape

(10,)

In [18]:
np1.ndim

1

### Create a multi-dimensinal array

In [13]:
my_matrix = [[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]

In [14]:
md_arr = np.array(my_matrix)

In [15]:
md_arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [16]:
md_arr.shape

(3, 4)

In [17]:
md_arr.ndim

2

In [19]:
md_arr.dtype

dtype('int32')

In [36]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=float)

In [37]:
arr1

array([1., 2., 3., 4., 5.])

In [38]:
arr1.dtype

dtype('float64')

In [39]:
lst_odd_size = [[1, 2, 3], [4, 5], [7, 8, 9]]
lst_odd_size

[[1, 2, 3], [4, 5], [7, 8, 9]]

In [40]:
md_arr_odd = np.array(lst_odd_size)

In [41]:
md_arr_odd

array([list([1, 2, 3]), list([4, 5]), list([7, 8, 9])], dtype=object)

In [42]:
md_arr_odd.shape

(3,)

In [43]:
md_arr_odd.ndim

1

In [44]:
md_arr_odd.dtype

dtype('O')

In [45]:
my_list = [1, 2, 3, 4, 5, 6]

In [46]:
arr1 = np.array(my_list, dtype='i')

In [47]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [48]:
arr1.shape

(6,)

In [49]:
arr2 = arr1.reshape(3, 2)

In [50]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [51]:
arr2.ndim

2

In [52]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [53]:
arr3 = arr1.reshape(3, -1)

In [54]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [55]:
arr3.shape

(3, 2)

In [61]:
my_list1 = list(range(1, 6))
my_list2 = list(range(10, 15))
my_list3 = list(range(20, 25))

In [62]:
my_list1, my_list2, my_list3

([1, 2, 3, 4, 5], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24])

In [63]:
mul_arr = np.array([my_list1, my_list2, my_list3])

In [64]:
mul_arr

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [65]:
mul_arr.shape

(3, 5)

In [67]:
mul_arr_15 = mul_arr.reshape(1, 15)

In [69]:
mul_arr_15.shape

(1, 15)

In [70]:
mul_arr_15.ndim

2

In [71]:
mul_arr_51 = mul_arr_15.reshape(15, 1)

In [72]:
mul_arr_51.shape

(15, 1)

In [73]:
mul_arr_51.ndim

2

In [74]:
mul_arr_15

array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24]])

In [75]:
mul_arr_51

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [10],
       [11],
       [12],
       [13],
       [14],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [77]:
a.ndim

1

In [78]:
a.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
b = a.reshape(6, 4, 1)

In [80]:
b.ndim

3

In [81]:
b

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [82]:
c = a.reshape(3, 2, 4)

In [83]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [84]:
x = np.array([1, 2, 3], dtype = np.int8)

In [85]:
print(x.itemsize)

1


In [86]:
x = np.array([1, 2, 3], dtype = np.int64)

In [87]:
print(x.itemsize)

8


In [89]:
x = np.array([1, 2, 3], dtype = np.int32)
print(x.itemsize)

4


In [90]:
arr1 = np.arange(0, 11, 2)

In [91]:
arr1

array([ 0,  2,  4,  6,  8, 10])

In [98]:
arr = np.random.randint(20, 30, 10)

In [99]:
arr

array([20, 27, 28, 26, 25, 23, 22, 22, 26, 21])

In [100]:
len(arr)

10

In [101]:
# index starts with zero
arr[0]

20

In [102]:
arr[5:8]

array([23, 22, 22])

In [103]:
arr[:3]

array([20, 27, 28])

In [104]:
arr[3:]

array([26, 25, 23, 22, 22, 26, 21])

In [105]:
arr[-1]

21

In [106]:
# Broadcasting
# Array slices are *actually* views on the original array
# That means, data isn't copied, and any modifications to the view would be reflected back to the source array

In [107]:
arr

array([20, 27, 28, 26, 25, 23, 22, 22, 26, 21])

In [108]:
arr[0:5] = 99

In [109]:
arr

array([99, 99, 99, 99, 99, 23, 22, 22, 26, 21])

In [110]:
new_arr = np.random.randint(10, 20, 10)

In [111]:
new_arr

array([13, 11, 16, 13, 15, 12, 13, 17, 10, 16])

In [112]:
slice_new_arr = new_arr[0:5]

In [113]:
slice_new_arr

array([13, 11, 16, 13, 15])

In [114]:
slice_new_arr[0] = 100

In [115]:
slice_new_arr

array([100,  11,  16,  13,  15])

In [116]:
new_arr

array([100,  11,  16,  13,  15,  12,  13,  17,  10,  16])

In [117]:
slice_new_arr[:] = 111

In [118]:
slice_new_arr

array([111, 111, 111, 111, 111])

In [119]:
new_arr

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [120]:
new_arr_copy = new_arr.copy()

In [121]:
new_arr

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [122]:
new_arr_copy

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [123]:
new_arr_copy[0:5] = 123

In [124]:
new_arr_copy

array([123, 123, 123, 123, 123,  12,  13,  17,  10,  16])

In [125]:
new_arr

array([111, 111, 111, 111, 111,  12,  13,  17,  10,  16])

In [126]:
a = list(range(1, 11))

In [127]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [128]:
b = a[0:5]

In [129]:
b

[1, 2, 3, 4, 5]

In [130]:
b[0] = 100

In [131]:
b

[100, 2, 3, 4, 5]

In [132]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [133]:
b[0:3] = 123

TypeError: can only assign an iterable

In [134]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [135]:
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [136]:
x

array([[1., 2.],
       [3., 4.]])

In [137]:
y

array([[5., 6.],
       [7., 8.]])

In [138]:
x.ndim, y.ndim

(2, 2)

In [139]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [140]:
x - y

array([[-4., -4.],
       [-4., -4.]])

In [141]:
y - x

array([[4., 4.],
       [4., 4.]])

In [142]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [143]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [144]:
np.subtract(y, x)

array([[4., 4.],
       [4., 4.]])

In [145]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [146]:
x

array([[1., 2.],
       [3., 4.]])

In [147]:
y

array([[5., 6.],
       [7., 8.]])

In [148]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [149]:
# dot product

In [150]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [151]:
x, y

(array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]]))

In [152]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [153]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [154]:
x

array([[1., 2.],
       [3., 4.]])

In [156]:
print(np.sum(x)) # compute sum of all elements of the array

10.0


In [157]:
print(np.sum(x, axis=0)) # compute sum of each column

[4. 6.]


In [158]:
print(np.sum(x, axis=1)) # compute sum of each row

[3. 7.]


In [159]:
arr = np.arange(15)

In [160]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [164]:
arr = arr.reshape(3, 5)

In [165]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [166]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [167]:
np.max(arr)

14

In [168]:
np.min(arr)

0

In [169]:
x

array([[1., 2.],
       [3., 4.]])

In [170]:
y

array([[5., 6.],
       [7., 8.]])

In [172]:
np.maximum(x, y)

array([[5., 6.],
       [7., 8.]])

In [173]:
a = np.array([[1, 2], [2, 1]], dtype=np.float64)
b = np.array([[2, 1], [1, 2]], dtype=np.float64)

In [174]:
np.maximum(a, b)

array([[2., 2.],
       [2., 2.]])

In [175]:
np.minimum(a, b)

array([[1., 1.],
       [1., 1.]])

In [176]:
a

array([[1., 2.],
       [2., 1.]])

In [177]:
b

array([[2., 1.],
       [1., 2.]])

In [178]:
zeros_a = np.zeros_like(a)

In [179]:
zeros_a

array([[0., 0.],
       [0., 0.]])

In [180]:
ones_a = np.ones_like(a)

In [181]:
ones_a

array([[1., 1.],
       [1., 1.]])

In [183]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [184]:
a

array([[1., 2.],
       [2., 1.]])

In [190]:
i = 10